brew install getantibody/tap/antibody
brew install zsh
brew install vim
brew install wget
brew install git
brew install heroku/brew/heroku
brew install hub
brew install darksky-weather
brew install cmatrix
