brew install zsh
brew install vim
brew install wget
brew install git
brew install heroku/brew/heroku
brew install hub
brew install darksky-weather
brew install cmatrix
brew install zplug
brew install tmux
brew install docker
brew install ruby
brew install redis
brew install tmuxinator