brew tap homebrew/science
brew install opencv
brew install tesseract
brew install android-platform-tools
brew install nvm
brew install watchman
brew install go
brew install rbenv
brew install youtube-dl
brew install antibody
brew install docker
brew install docker-compose
brew install ffmpeg
brew install gifsicle
brew install git
brew install graphviz
brew install grc
brew install hub
brew install htop-osx
brew install imagemagick
brew install node
brew install redis
brew install shellcheck
brew install terminal-notifier
brew install the_silver_searcher
brew install task
brew install tmux
brew install unrar
brew install vim
brew install wakatime-cli
brew install wget
brew install zsh
brew install z
