call plug#begin()
Plug 'https://github.com/tpope/vim-sensible.git'
Plug 'https://github.com/scrooloose/nerdtree'
Plug 'https://github.com/ctrlpvim/ctrlp.vim'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'https://github.com/ntpeters/vim-better-whitespace'
Plug 'https://github.com/mhinz/vim-signify.git'
Plug 'https://github.com/itchyny/lightline.vim'
Plug 'https://github.com/mhinz/vim-startify'
Plug 'ambv/black'
call plug#end()
