" https://github.com/vim/vim/issues/3117#issuecomment-402622616
if has('python3')
  silent! python3 1
endif

set nocompatible " Use Vim settings rather than Vi settings.
let mapleader = "," " Set leader key to comma.

" Theme settings.
syntax enable " Switch syntax highlighting on.
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1 " Remove this line if using the default palette.
set background=dark


" Options.
set wildignore=*.swp,*.bak,*.pyc,*.class,*.p,*~ " Ignore compiled files and other unnecessary stuff
set backspace=indent,eol,start " Make backspace behave properly.
set ruler " Always show current position.
set cmdheight=2 " Height of the command bar.
set ignorecase " Ignore case when searching.
set hlsearch " Highlight search results.
set incsearch " Makes search act like search in modern browsers.
set magic " For regular expressions turn magic on.
set expandtab " Use spaces instead of tabs.
set smarttab " Be smart when using tabs.
set autoread " Set to auto read when a file is changed from the outside.
filetype plugin indent on " Turn on filetype plugin and indent autodetection.
set autowrite " Automatically write before running commands.
set number " Display line numbers.
set title " Make xterm inherit title from vim.
set laststatus=2 " Always show status line.
set hidden " Hide buffers instead of closing them (not be forced to write/undo changes when opening a new file)
set nowrap " Disable line wrapping.
set lazyredraw " Redraw only when we need to
set mouse=a " Allow mouse scrolling
let g:netrw_dirhistmax = 0 " Prevent writing junk files.
autocmd User Startified setlocal buftype=

" Disable automatic creation of backup/swap files.
set nobackup
set nowritebackup
set noswapfile

" Set undo and history limit.
set undolevels=1000
set history=1000

" 1 tab == 4 spaces.
set shiftwidth=4
set tabstop=4

" Set indentation style for specific languages.
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType typescript setlocal shiftwidth=2 tabstop=2
autocmd FileType typescriptreact setlocal shiftwidth=2 tabstop=2
autocmd FileType ruby setlocal shiftwidth=2 tabstop=2
autocmd FileType c setlocal shiftwidth=8 tabstop=8
autocmd FileType make setlocal shiftwidth=8 tabstop=8
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType python setlocal shiftwidth=4 tabstop=4
autocmd FileType vue setlocal shiftwidth=2 tabstop=2

" Folding settings.
set foldmethod=syntax
set foldlevel=1
set foldclose=all
set foldnestmax=1
let javaScript_fold=1

" Load plugins and mappings.
source ~/dotfiles/vim/mappings.vim
source ~/dotfiles/vim/plugins.vim

colorscheme tokyonight " Set colorscheme
